spring:
  graphql:
    graphiql:
      enabled: true
  data:
    mongodb:
      database: flights
      port: 27017

server:
  port: 8080

graphql:
  datetime:
    scalars:
      local-date-time:
        format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
      zone-conversion-enabled: true